# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Epicures.' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  # Pods for Epicures.

  target 'Epicures.UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
